version: 1.0.0.{build}
image: Visual Studio 2019
configuration:
- Release
- Debug
platform: Any CPU
shallow_clone: true
install:
- ps: AppVeyor\install.ps1
before_build:
- cmd: nuget restore
build:
  project: GDPIControl.sln
  verbosity: minimal
artifacts:
- path: GDPIControl\bin\Release
  name: GDPIControl
deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: GDPIControl $(AppVersion)
  description: "No changelog"
  auth_token:
    secure: 9NRTNKyVHpRNaenx8/anaILCi7GN/qSFnXAbGAzx2oCoIUJsiAhuxP0MHIBG/V8k
  artifact: GDPIControl
  draft: false
  prerelease: true
  on:
    configuration: Release
    appveyor_repo_tag: true