name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      Solution_Name: GDPIControl.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Set VERSION
      shell: pwsh
      run: |
        dotnet tool install -g minver-cli --version 2.5.0
        $version = minver -t v -d preview
        $number = $version.Split('-')[0]
        echo "GITHUB_ENV: VERSION=$version"
        echo "VERSION=$version" >> $GITHUB_ENV
  
    - name: Build the application
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: GDPIControl
        path: |
          GDPIControl\bin\${{matrix.configuration}}\net5.0-windows\*.*(dll|exe)
          GDPIControl\bin\${{matrix.configuration}}\net5.0-windows\GDPI\
        if-no-files-found: error
